/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifnmg.projetocinemapoo.gui;

import br.edu.ifnmg.projetocinemapoo.dao.FilmeDao;
import br.edu.ifnmg.projetocinemapoo.dao.SalaDao;
import br.edu.ifnmg.projetocinemapoo.dao.SessaoDao;
import br.edu.ifnmg.projetocinemapoo.entity.Filme;
import br.edu.ifnmg.projetocinemapoo.entity.Sala;
import br.edu.ifnmg.projetocinemapoo.entity.Sessao;
import br.edu.ifnmg.projetocinemapoo.enums.Audio;
import com.toedter.calendar.JDateChooser;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class CadastroSessao extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroSessa
     */
    private CadastroSessao() {
        initComponents();

        rdbDublado.setSelected(true);
    }

    private static CadastroSessao cadastroSessao;

    public static CadastroSessao getInstancia() {
        if (cadastroSessao == null) {
            cadastroSessao = new CadastroSessao();
        }
        return cadastroSessao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cmbFilme = new javax.swing.JComboBox<>();
        lblFilme = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dtcHorario = new com.toedter.calendar.JDateChooser();
        hmcHorario = new com.toedter.calendar.JHourMinuteChooser();
        cmbSala = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rdbDublado = new javax.swing.JRadioButton();
        rdbLegendado = new javax.swing.JRadioButton();
        txtPreco = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de sessão");

        cmbFilme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbFilme.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFilmeItemStateChanged(evt);
            }
        });
        cmbFilme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbFilmeFocusGained(evt);
            }
        });

        lblFilme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFilme.setText("Filme:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Horario:");

        hmcHorario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbSala.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbSala.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbSalaFocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Sala:");

        buttonGroup1.add(rdbDublado);
        rdbDublado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdbDublado.setText("Dublado");

        buttonGroup1.add(rdbLegendado);
        rdbLegendado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdbLegendado.setText("Legendado");

        txtPreco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Preco:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lblFilme)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbFilme, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hmcHorario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dtcHorario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSalvar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPreco)
                            .addComponent(cmbSala, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rdbDublado)
                                .addGap(96, 96, 96)
                                .addComponent(rdbLegendado)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilme)
                    .addComponent(cmbFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dtcHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hmcHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbDublado)
                    .addComponent(rdbLegendado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if(!validarCampos()){
            return;
        }
        Sessao s = new Sessao();
        s.setFilme((Filme) cmbFilme.getSelectedItem());
        s.setHorario(converterParaLocalDateTime(dtcHorario.getDate(), dtcHorario, hmcHorario.getTime()));
        s.setSala((Sala) cmbSala.getSelectedItem());
        if (rdbDublado.isSelected()) {
            s.setAudio(Audio.DUBLADO);
        } else {
            s.setAudio(Audio.LEGENDADO);
        }
        s.setIngressosVendidos(0);
        s.setValorSessao(Double.parseDouble(txtPreco.getText()));

        new SessaoDao().salvar(s);
        limparCampos();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cmbFilmeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFilmeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFilmeItemStateChanged

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void cmbFilmeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbFilmeFocusGained
        // TODO add your handling code here:
        atualizarComboBox();
    }//GEN-LAST:event_cmbFilmeFocusGained

    private void cmbSalaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbSalaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSalaFocusGained

    private LocalDateTime converterParaLocalDateTime(Date data, JDateChooser calendario, String tempo) {
        if (data == null) {
            calendario.setDate(new Date());
            return LocalDateTime.now();
        }
        LocalDate ld = data.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        return LocalDateTime.parse(ld.toString() + "T"
                + LocalTime.parse(tempo, DateTimeFormatter.ofPattern("hh:mm a")));
    }

    protected void limparCampos() {
        cmbFilme.setSelectedIndex(-1);
        cmbSala.setSelectedIndex(-1);
        txtPreco.setText("");
        dtcHorario.setDate(null);
        hmcHorario.setCurrentTime();
        rdbDublado.setSelected(true);
    }

    protected void atualizarComboBox() {
        // Definição do model do Filme
        DefaultComboBoxModel<Filme> ComboBoxModelF = new DefaultComboBoxModel<>();
        List<Filme> filmes = new FilmeDao().localizarTodos();
        ComboBoxModelF.addAll(filmes);
        cmbFilme.setModel(ComboBoxModelF);

        //Definicao do model de Sala
        DefaultComboBoxModel<Sala> ComboBoxModelS = new DefaultComboBoxModel<>();
        List<Sala> salas = new SalaDao().localizarTodos();
        ComboBoxModelS.addAll(salas);
        cmbSala.setModel(ComboBoxModelS);
    }

    private Boolean validarCampos() {

        Filme f = (Filme) cmbFilme.getSelectedItem();
        if (f == null) {
            JOptionPane.showMessageDialog(null, "Escolha um filme.");
            return false;
        }

        Date d = dtcHorario.getDate();
        if (d == null) {
            JOptionPane.showMessageDialog(null, "Data inválida.");
            return false;
        }

        Sala s = (Sala) cmbSala.getSelectedItem();
        if (s == null) {
            JOptionPane.showMessageDialog(null, "Escolha uma sala.");
            return false;
        }
        
        Double n;
        try {
            n = Double.parseDouble(txtPreco.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Preço inválido");
            return false;
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Filme> cmbFilme;
    private javax.swing.JComboBox<Sala> cmbSala;
    private com.toedter.calendar.JDateChooser dtcHorario;
    private com.toedter.calendar.JHourMinuteChooser hmcHorario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFilme;
    private javax.swing.JRadioButton rdbDublado;
    private javax.swing.JRadioButton rdbLegendado;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
