/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifnmg.projetocinemapoo.gui;

import br.edu.ifnmg.projetocinemapoo.dao.GuicheDao;
import br.edu.ifnmg.projetocinemapoo.dao.SessaoDao;
import br.edu.ifnmg.projetocinemapoo.dao.VendaDao;
import br.edu.ifnmg.projetocinemapoo.entity.Funcionario;
import br.edu.ifnmg.projetocinemapoo.entity.Guiche;
import br.edu.ifnmg.projetocinemapoo.entity.Ingresso;
import br.edu.ifnmg.projetocinemapoo.entity.Sessao;
import br.edu.ifnmg.projetocinemapoo.entity.Venda;
import static java.awt.event.ItemEvent.SELECTED;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class CadastroVenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form Venda
     */
    private Funcionario funcionario;

    private CadastroVenda(Funcionario f) {
        initComponents();

        funcionario = f;
    }

    private static CadastroVenda cadastroVenda;

    public static CadastroVenda getInstancia(Funcionario f) {
        if (cadastroVenda == null) {
            cadastroVenda = new CadastroVenda(f);
        }
        return cadastroVenda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblQuantidade = new javax.swing.JLabel();
        chkMeiaEntrada = new javax.swing.JCheckBox();
        btnAdicionarIngresso = new javax.swing.JButton();
        btnRemoverUltimo = new javax.swing.JButton();
        lblPrecoTotal = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        cmbSessao = new javax.swing.JComboBox<>();
        cmbGuiche = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblDuracao = new javax.swing.JLabel();
        lblSala = new javax.swing.JLabel();
        txtHorario = new javax.swing.JTextField();
        txtDuracao = new javax.swing.JTextField();
        txtSala = new javax.swing.JTextField();
        lblClassificacao = new javax.swing.JLabel();
        txtClassificacao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        txtPrecoTotal = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Venda");

        lblQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantidade.setText("Quantidade: 0");

        chkMeiaEntrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkMeiaEntrada.setText("Meia Entrada");

        btnAdicionarIngresso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdicionarIngresso.setText("Adicionar Ingresso");
        btnAdicionarIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarIngressoActionPerformed(evt);
            }
        });

        btnRemoverUltimo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRemoverUltimo.setText("Remover último");
        btnRemoverUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverUltimoActionPerformed(evt);
            }
        });

        lblPrecoTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrecoTotal.setText("Preco total:");

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        cmbSessao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbSessao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSessaoItemStateChanged(evt);
            }
        });
        cmbSessao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbSessaoFocusGained(evt);
            }
        });
        cmbSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSessaoActionPerformed(evt);
            }
        });

        cmbGuiche.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbGuiche.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbGuicheFocusGained(evt);
            }
        });
        cmbGuiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGuicheActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Guiche:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Sessao");

        lblHorario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHorario.setText("Horario:");

        lblDuracao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDuracao.setText("Duração:");

        lblSala.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSala.setText("Sala:");

        txtHorario.setEditable(false);
        txtHorario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtDuracao.setEditable(false);
        txtDuracao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracaoActionPerformed(evt);
            }
        });

        txtSala.setEditable(false);
        txtSala.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaActionPerformed(evt);
            }
        });

        lblClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblClassificacao.setText("Classificação:");

        txtClassificacao.setEditable(false);
        txtClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Preço:");

        txtPreco.setEditable(false);
        txtPreco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        txtPrecoTotal.setEditable(false);
        txtPrecoTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chkMeiaEntrada)
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbGuiche, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(btnAdicionarIngresso)
                                        .addGap(99, 99, 99)
                                        .addComponent(btnRemoverUltimo))
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(lblPrecoTotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(173, 173, 173)
                                        .addComponent(btnSalvar)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(lblDuracao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addGap(239, 239, 239)
                                        .addComponent(lblSala)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSala))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(lblHorario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(lblClassificacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPreco))))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lblQuantidade)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkMeiaEntrada)
                .addGap(3, 3, 3)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorario)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuracao)
                    .addComponent(txtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSala)
                    .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassificacao)
                    .addComponent(txtClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(lblQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarIngresso)
                    .addComponent(btnRemoverUltimo))
                .addGap(32, 32, 32)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(lblPrecoTotal)
                    .addComponent(txtPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private List<Ingresso> ingressos = new ArrayList<>();
    private void btnAdicionarIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarIngressoActionPerformed
        // TODO add your handling code here:
        if (cmbGuiche.getSelectedItem() == null || cmbSessao.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Selecione o Guichê e a Sessão");
        } else {
            Ingresso i = new Ingresso();
            Sessao s = new Sessao();
            s = (Sessao) cmbSessao.getSelectedItem();
            if (chkMeiaEntrada.isSelected()) {
                i.setMeiaEntrada(true);
            } else {
                i.setMeiaEntrada(false);
            }
            i.setPreco(s.getValorSessao());
            ingressos.add(i);
            atualizarIngressos();
            controleIngressos();
        }
    }//GEN-LAST:event_btnAdicionarIngressoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Venda v = new Venda();
        Sessao s;

        // ASSOCIA FUNCIONARIO QUE FEZ A VENDA AO GUICHE E
        // INCREMENTA O NUMERO DE INGRESSOS VENDIDOS DA SESSAO
        s = (Sessao) cmbSessao.getSelectedItem();
        s.vendeuIngressos(ingressos.size());
        new SessaoDao().salvar(s);

        v.setQuantidade((short) ingressos.size());
        v.setGuiche((Guiche) cmbGuiche.getSelectedItem());
        v.setSessao(s);
        v.setIngressos(ingressos);
        v.setFuncionario(funcionario);
        Double total = 0.0;
        for (Ingresso ingresso : ingressos) {
            total += ingresso.getPreco();
        }
        v.setValorTotal(total);
        new VendaDao().salvar(v);
        limparCampos();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnRemoverUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverUltimoActionPerformed
        // TODO add your handling code here:
        ingressos.remove(ingressos.size() - 1);
        atualizarIngressos();
        controleIngressos();
    }//GEN-LAST:event_btnRemoverUltimoActionPerformed

    private void cmbSessaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSessaoItemStateChanged
        // TODO add your handling code here
        if (evt.getStateChange() == SELECTED) {
            Sessao s = (Sessao) cmbSessao.getSelectedItem();
            txtClassificacao.setText(s.getFilme()
                    .getClassificacao().getDescription().replace("_", "+"));
            txtDuracao.setText(s.getFilme().getDuracao() + " minutos");
            txtHorario.setText(s.getHorario().
                    format(DateTimeFormatter.ofPattern("dd/MM/yyy hh:mm")));
            txtPreco.setText(s.getValorSessao().toString());
            txtSala.setText(s.getSala().getTela().getDescription().replace("_", ""));
        }
    }//GEN-LAST:event_cmbSessaoItemStateChanged

    private void cmbGuicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGuicheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGuicheActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracaoActionPerformed

    private void txtSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaActionPerformed

    private void cmbSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSessaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSessaoActionPerformed

    private void cmbGuicheFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbGuicheFocusGained
        // TODO add your handling code here:
        atualizarComboBox();
    }//GEN-LAST:event_cmbGuicheFocusGained

    private void cmbSessaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbSessaoFocusGained
        // TODO add your handling code here:
        atualizarComboBox();
    }//GEN-LAST:event_cmbSessaoFocusGained

    private void controleIngressos() {
        if (ingressos.isEmpty()) {
            cmbSessao.setEnabled(true);
            cmbGuiche.setEnabled(true);
        } else {
            cmbSessao.setEnabled(false);
            cmbGuiche.setEnabled(false);
        }
    }

    private void atualizarIngressos() {
        Double total = 0.0;
        for (Ingresso ingresso : ingressos) {
            total += ingresso.getPreco();
        }
        lblQuantidade.setText("Quantidade: " + ingressos.size());
        txtPrecoTotal.setText(total.toString());
    }

    protected void atualizarComboBox() {
        DefaultComboBoxModel<Sessao> ComboBoxS = new DefaultComboBoxModel<>();
        List<Sessao> sessoes = new SessaoDao().localizarTodos();
        ComboBoxS.addAll(sessoes);
        cmbSessao.setModel(ComboBoxS);

        DefaultComboBoxModel<Guiche> ComboBoxG = new DefaultComboBoxModel<>();
        List<Guiche> guiches = new GuicheDao().localizarTodos();
        ComboBoxG.addAll(guiches);
        cmbGuiche.setModel(ComboBoxG);
    }

    protected void limparCampos() {
        cmbGuiche.setSelectedIndex(-1);
        cmbSessao.setSelectedIndex(-1);
        chkMeiaEntrada.setSelected(false);
        ingressos.clear();
        atualizarIngressos();
        controleIngressos();
        txtClassificacao.setText(null);
        txtHorario.setText(null);
        txtDuracao.setText(null);
        txtPreco.setText(null);
        txtPrecoTotal.setText(null);
        txtSala.setText(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarIngresso;
    private javax.swing.JButton btnRemoverUltimo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkMeiaEntrada;
    private javax.swing.JComboBox<Guiche> cmbGuiche;
    private javax.swing.JComboBox<Sessao> cmbSessao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblClassificacao;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblPrecoTotal;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblSala;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtClassificacao;
    private javax.swing.JTextField txtDuracao;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtPrecoTotal;
    private javax.swing.JTextField txtSala;
    // End of variables declaration//GEN-END:variables
}
