/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifnmg.projetocinemapoo.gui;

import br.edu.ifnmg.projetocinemapoo.entity.Funcionario;
import br.edu.ifnmg.projetocinemapoo.enums.TipoFuncionario;

/**
 *
 * @author Lucas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private Principal(Funcionario F) {
        initComponents();
        
        if(F.getTipoFuncionario() != TipoFuncionario.GERENTE){
            mnuCadastrosFuncionario.setEnabled(false);
        }
    }
    
    public static Principal principal;
    
    public static Principal getInstancia(Funcionario F){
        if(principal == null){
            principal = new Principal(F);
        }
        return principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mnuArquivoSair = new javax.swing.JMenuItem();
        mnuCadastros = new javax.swing.JMenu();
        mnuCadastrosFuncionario = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        mnuRelatoriosFuncionarios = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        mnuArquivo.setText("Arquivo");

        mnuArquivoSair.setText("Sair");
        mnuArquivo.add(mnuArquivoSair);

        jMenuBar1.add(mnuArquivo);

        mnuCadastros.setText("Cadastros");

        mnuCadastrosFuncionario.setText("Funcionario");
        mnuCadastros.add(mnuCadastrosFuncionario);

        jMenuBar1.add(mnuCadastros);

        mnuRelatorios.setText("Relatorios");

        mnuRelatoriosFuncionarios.setText("Funcionarios");
        mnuRelatorios.add(mnuRelatoriosFuncionarios);

        jMenuBar1.add(mnuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenuItem mnuArquivoSair;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenuItem mnuCadastrosFuncionario;
    private javax.swing.JMenu mnuRelatorios;
    private javax.swing.JMenuItem mnuRelatoriosFuncionarios;
    // End of variables declaration//GEN-END:variables
}
