/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifnmg.projetocinemapoo.gui;

import br.edu.ifnmg.projetocinemapoo.dao.ConexaoBd;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dayan
 */
public class RelatorioSala extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioSala
     */
    public RelatorioSala() {
        initComponents();
    }
    
     private static RelatorioSala relatorioSala;
     
      public static RelatorioSala getInstancia(){
        if(relatorioSala == null){
            relatorioSala  = new RelatorioSala();
        }
        return relatorioSala;
    }
    
      
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRelatorioSalas = new javax.swing.JPanel();
        btnExibirRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Salas");
        setName("frmRelatorioSalas"); // NOI18N
        setResizable(false);

        btnExibirRelatorio.setText("Exibir Relatório");
        btnExibirRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRelatorioSalasLayout = new javax.swing.GroupLayout(pnlRelatorioSalas);
        pnlRelatorioSalas.setLayout(pnlRelatorioSalasLayout);
        pnlRelatorioSalasLayout.setHorizontalGroup(
            pnlRelatorioSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRelatorioSalasLayout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(btnExibirRelatorio)
                .addContainerGap())
        );
        pnlRelatorioSalasLayout.setVerticalGroup(
            pnlRelatorioSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRelatorioSalasLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(btnExibirRelatorio)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRelatorioSalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRelatorioSalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExibirRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirRelatorioActionPerformed
        // TODO add your handling code here:
        
        try(InputStream in = getClass().getResourceAsStream("/RelatorioSalas.jasper")){
        
         JasperPrint jasperPrint = JasperFillManager.fillReport(in, null, ConexaoBd.getConexao());
         JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
         
//         jasperViewer.setTitle("Relatório de Salas");
//         jasperViewer.setVisible(true);
        
         
         JDialog dialog = new JDialog(this);
         dialog.setContentPane(jasperViewer.getContentPane());
         dialog.setSize(jasperViewer.getSize());
         dialog.setTitle("Relatório de Salas");
         dialog.setModal(true);
         dialog.setVisible(true);
        
        
        } catch (IOException ex) {
            Logger.getLogger(RelatorioSala.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(RelatorioSala.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btnExibirRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExibirRelatorio;
    private javax.swing.JPanel pnlRelatorioSalas;
    // End of variables declaration//GEN-END:variables
}
